package reports;

import javax.swing.*;
import java.awt.*;
import dao.*;
import admin.SystemReportsFrame;

public class FullReportFrame extends JFrame {

    private EventDAO eventDAO;
    private RegistrationDAO registrationDAO;
    private UserDAO userDAO;
    private int userId;

    public FullReportFrame(int userId) {
        this.userId = userId;
        
        eventDAO = new EventDAO();
        registrationDAO = new RegistrationDAO();
        userDAO = new UserDAO();

        setTitle("Full System Report");
        setSize(550, 500);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);

        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));

        JTextArea txtReport = new JTextArea();
        txtReport.setEditable(false);
        txtReport.setLineWrap(true);
        txtReport.setWrapStyleWord(true);
        txtReport.setFont(new Font("Arial", Font.PLAIN, 12));
        
        JScrollPane scrollPane = new JScrollPane(txtReport);
        scrollPane.setPreferredSize(new Dimension(500, 400));
        mainPanel.add(scrollPane, BorderLayout.CENTER);

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 0));
        buttonPanel.setBorder(BorderFactory.createEmptyBorder(10, 0, 0, 0));
        
        JButton btnRefresh = new JButton("Refresh");
        JButton btnBack = new JButton("Back");
        
        Dimension btnSize = new Dimension(100, 30);
        btnRefresh.setPreferredSize(btnSize);
        btnBack.setPreferredSize(btnSize);
        
        buttonPanel.add(btnRefresh);
        buttonPanel.add(btnBack);
        mainPanel.add(buttonPanel, BorderLayout.SOUTH);

        setContentPane(mainPanel);

        btnRefresh.addActionListener(e -> loadReportData(txtReport));
        btnBack.addActionListener(e -> {
            new SystemReportsFrame(userId).setVisible(true);
            dispose();
        });

        loadReportData(txtReport);
    }

    private void loadReportData(JTextArea txtReport) {
        try {
            StringBuilder sb = new StringBuilder();
            sb.append("════════════════ FULL SYSTEM REPORT ════════════════\n\n");

            int totalUsers = userDAO.getTotalUsersCount();
            int adminUsers = userDAO.getUsersCountByRole("admin");
            int organizerUsers = userDAO.getUsersCountByRole("organizer");
            int attendeeUsers = userDAO.getUsersCountByRole("attendee");

            sb.append("USERS STATISTICS:\n");
            sb.append("────────────────────────────────────────\n");
            sb.append("• Total Users: ").append(totalUsers).append("\n");
            sb.append("• Administrators: ").append(adminUsers).append("\n");
            sb.append("• Organizers: ").append(organizerUsers).append("\n");
            sb.append("• Attendees: ").append(attendeeUsers).append("\n\n");

            int totalEvents = eventDAO.getTotalEventsCount();
            int availableEvents = eventDAO.getAvailableEventsCount();
            int fullEvents = eventDAO.getFullEventsCount();

            sb.append("EVENTS STATISTICS:\n");
            sb.append("────────────────────────────────────────\n");
            sb.append("• Total Events: ").append(totalEvents).append("\n");
            sb.append("• Available Events: ").append(availableEvents).append("\n");
            sb.append("• Full Events: ").append(fullEvents).append("\n\n");

            int totalRegistrations = registrationDAO.getTotalRegistrationsCount();
            double avgRegistrationsPerEvent = totalEvents > 0 ? (double) totalRegistrations / totalEvents : 0;

            sb.append("REGISTRATIONS STATISTICS:\n");
            sb.append("────────────────────────────────────────\n");
            sb.append("• Total Registrations: ").append(totalRegistrations).append("\n");
            sb.append("• Avg. Registrations/Event: ").append(String.format("%.1f", avgRegistrationsPerEvent)).append("\n\n");

            sb.append("SYSTEM SUMMARY:\n");
            sb.append("────────────────────────────────────────\n");
            sb.append("• Database: Connected\n");
            sb.append("• Last Updated: ").append(new java.util.Date()).append("\n");
            sb.append("• Report Generated By: System Administrator\n");

            txtReport.setText(sb.toString());

        } catch (Exception ex) {
            txtReport.setText("Error loading report data: " + ex.getMessage());
        }
    }
}